django_project/frontend/static/js/map.js
fix #226 - use mapquest for base map
=> fix #226 - use mapquest for base map

django_project/core/base_static/css/map.css
@timlinux location icon not visible
=> #327 | location icon not visible

django_project/frontend/templates/index.html
=> #321 | update graph

django_project/frontend/templates/index.html
=> #318 | open map in new tab

django_project/core/base_static/css/map.css
@timlinux already fix it, it is css changes
=> #324 | fixing map not shown

django_project/core/base_static/css/map.css, django_project/frontend/static/js/app.js, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html
=> #328 | sharing locality in map

django_project/core/base_static/css/site.css, django_project/core/base_static/js/custom-jquery.js, django_project/frontend/templates/index.html
=> Jquery bug fix

django_project/frontend/static/js/app.js, django_project/frontend/static/js/map.js
@timlinux from just url to lacality t
"see [hospital_name] [url]"
=> #352 | updating share twitter

django_project/core/settings/project.py, django_project/frontend/static/js/map.js, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html, django_project/frontend/views.py
@markherringer 
you could try the UI with this PR
=> #183 | geoname and location name search

django_project/frontend/static/js/localitySidebar.js
@timlinux 
fixing by set default first before showing info
=> #339 | Health site displays location name for another health site

django_project/core/base_static/js/custom-jquery.js
@timlinux @markherringer 
now, front page has hashtag on the url
=> #348 | share sections of the home page

django_project/core/base_static/css/home.css, django_project/core/base_static/js/custom-jquery.js, django_project/frontend/templates/map.html
=> #347 fix scroll to country-data

django_project/frontend/static/js/localitySidebar.js
=> #358 | change 'no information' to 'needs information'

django_project/frontend/static/js/map.js
@timlinux 
zoom out map when go to localities up to 2 level
=> #394 | location zoom level from country data map

django_project/frontend/static/js/localitySidebar.js, django_project/frontend/static/js/map.js
@timlinux 
removed cache that saved uuid, that make when user go to map, it will load last localitiy
=> #366 | see the map default view

django_project/core/settings/project.py, django_project/frontend/static/js/nav_bar.js, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html
@timlinux update search in map
=> implemented search for map

django_project/frontend/templates/map.html
=> #377 | change identity of user in healthsite provenance

django_project/frontend/static/js/nav_bar.js
=> #328 | update social share copy

django_project/core/base_static/js/custom-jquery.js, django_project/frontend/templates/index.html
=> #386 | remove latest updates from home page

django_project/frontend/templates/index.html
=> #385 | Accessible copy update

django_project/core/base_templates/base.html
add search function on base.html
=> update search on base.html

django_project/social_users/templates/social_users/signinpage.html
=> #409 | fixing alignment signing

deployment/docker/REQUIREMENTS-dev.txt, deployment/docker/REQUIREMENTS.txt, django_project/core/base_static/css/map.css, django_project/frontend/static/js/localitySidebar.js, django_project/frontend/templates/map.html, django_project/frontend/views.py, django_project/localities/urls.py, django_project/localities/views.py
Show default in map view.
Showing list of countries and it's number of healthsite and percentage of completness
=> #360 | map-default-view

django_project/frontend/static/js/map.js, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html, django_project/frontend/views.py, django_project/localities/views.py
@markherringer 
Added polygon for country. in frontend and map view.
=> add polygon for country

django_project/core/base_static/css/map.css, django_project/core/base_static/js/custom-jquery.js, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html
- removed Browse Map button
- added active state to the button onclick
- show search field on the search button click
=> Icons navigation, Logos links

django_project/frontend/templates/index.html
#378 footer link
#388 google plus in the footer
=> UI updates

django_project/core/base_static/css/map.css, django_project/core/base_static/css/site.css, django_project/core/base_static/js/custom-jquery.js, django_project/frontend/templates/map.html
- put the copy on the place of the icons
- script update to count the height of the map and sidebar according to
the search bar state
- menu z-index, to fix the map credits issue
=> #510 update

django_project/localities/models.py, django_project/localities/tasks.py
it seems that when worker is started, database is still working, that need to retry
=> Fixing data loader for admin

django_project/core/base_static/css/site.css, django_project/core/base_templates/base.html, django_project/social_users/templates/social_users/profile.html, django_project/social_users/templates/social_users/signinpage.html
- mobile version fix for social sign-on
- profile page update and mobile version fix
=> #549, #554

django_project/core/base_static/css/jquery.cookiebar.css, django_project/core/base_static/css/site.css, django_project/core/base_static/js/custom-functions.js, django_project/frontend/templates/index.html
=> #556 terms of use

django_project/localities/management/commands/clean_localities.py, django_project/localities/management/commands/generate_masterization_by_cluster.py, django_project/localities/models.py
- now masterization will check overlap
- deciding master by newest locality that raw data
- now, when set master, it will overide synonyms value if master doesn't have data yet
=> Improve masterization

django_project/core/base_static/css/site.css, django_project/core/base_templates/base.html, django_project/core/settings/project.py, django_project/frontend/static/js/locality-sidebar.js, django_project/frontend/static/js/nav-bar.js, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html, django_project/frontend/views.py, django_project/localities/management/commands/harvest_what3words.py, django_project/localities/models.py, django_project/localities/signals.py, django_project/localities/urls.py, django_project/localities/utils.py, django_project/localities/views.py
- Added what3word attribute
- search by what3words
=> added what3words

django_project/core/base_static/css/map.css, django_project/core/base_templates/base.html, django_project/frontend/static/js/cluster-layer.js, django_project/frontend/static/js/custom-functions.js, django_project/frontend/static/js/locality-sidebar.js, django_project/frontend/static/js/map-page.js, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html, django_project/localities/admin.py, django_project/localities/masterization.py, django_project/localities/models.py, django_project/localities/utils.py, django_project/localities/views.py
=> update report popup and behaviour

deployment/Makefile
=> Tweaks to Makefile

django_project/localities/admin.py, django_project/localities/management/commands/generate_countries.py
@markherringer 
countries could be cleaning in admin now
this fix #803
=> update admin to show countries

django_project/api/urls.py, django_project/api/views/api_view.py, django_project/core/base_static/css/map.css, django_project/frontend/static/js/custom-functions.js, django_project/frontend/static/js/locality-sidebar.js, django_project/localities/views.py
this fixes #812 , fixes #813 , fixes #815
=> update text for masterization, api/v1 -> wiki

django_project/frontend/static/js/custom-functions.js
=> fixin bug, map not loaded in landing page

django_project/frontend/views.py, django_project/localities/utils.py
this fix error on :
https://healthsites.io/map?attribute=Community%20Health%20Centre&uuid=88f8c7e998b74941bfe4a1cafe7c8927
and also tag too
=> fixing NaN on attribute and tag filter

django_project/api/urls.py
fix API url for getting synonym
=> version 1.7.3 : hot fix

README.md
Please review this simple pull request.
=> Fix for #851

django_project/localities/management/commands/generate_shapefile.py, django_project/localities/models.py
this fixes #911 , fixes #893 
Finally found the error
=> Fixes bugs

deployment/script/osm/cleaning_osm.sql, deployment/script/osm/get_files.sh
=> fix import with points and use docker bash script

django_project/api/views/locality_search.py, django_project/localities/models.py
I was not able to really check/test on my laptop, because no fixtures :( Let me know if something went wrong.
For the description, please see https://github.com/healthsites/healthsites/issues/921
=> Fix pagination when search is done by name

.travis.yml, django_project/core/settings/prod.py, django_project/frontend/views.py, django_project/localities/management/commands/generate_countries.py, django_project/localities/management/commands/generate_countries_cache.py, django_project/localities/tests/test_views.py, django_project/localities/utils.py, django_project/localities/views.py
as described here: http://sentry.kartoza.com/sentry/healtsitesio/getting-started/python-django/
The sentry was installed and configured already, I just updated dsn and release config.
=> updates sentry configuration

django_project/core/base_templates/base.html, django_project/frontend/templates/index.html, django_project/frontend/templates/map.html
Change strapline to "Building an open data commons of health facility data with OpenStreetMap"
=> Update Strapline - Fix #956

deployment/docker-osm-compose.yml
Change docker osmenrich image name typo
=> change image name of osm-enrich

deployment/docker-osm-healthcare/mapping.yml, django_project/api/api_views/v2/facilities/base_api.py, django_project/api/api_views/v2/facilities/detail.py, django_project/api/api_views/v2/facilities/list.py, django_project/api/serializer/api_locality.py, django_project/api/urls.py, django_project/frontend/static/js/cluster-layer.js, django_project/frontend/static/js/map-functionality.js, django_project/frontend/static/js/utilities.js, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/shared.js, django_project/frontend/static/scripts/views/map-sidebar/locality-detail.js, django_project/frontend/static/scripts/views/statistic/pie.js, django_project/frontend/static/scripts/views/statistic/view.js, django_project/frontend/templates/map.html, django_project/localities/map_clustering.py, django_project/localities_osm/admin.py, django_project/localities_osm/models/locality.py, django_project/localities_osm/serializer/locality_osm.py
this fix : https://github.com/healthsites/healthsites/issues/1096
- Update frontend of locality detail to use detail from osm.
- Update completeness by checking mandatory fields filled or not.
- Showing polygon if it is way
TODO: edit/add locality.
@timlinux should we add polygon geometry when edit/add? 
if not, we should disable edit for way type
=> update locality sidebar using docker osm data

deployment/Makefile, deployment/docker-osm-healthcare/mapping.yml, django_project/api/api_views/v2/facilities/list.py, django_project/frontend/static/css/map/locality-sidebar.css, django_project/localities_osm/README.md, django_project/localities_osm/admin.py, django_project/localities_osm/models/locality.py, django_project/localities_osm/serializer/locality_osm.py
Update mapping.yml with finalized data : https://docs.google.com/spreadsheets/d/1P11VJPocQ5EkmoFaTMItg3z6Rdon2A1M2kIqqjIc-Cw/edit#gid=1195977473
Also update code accordingly
=> update mapping data with finalized data

django_project/localities/map_clustering.py, django_project/localities_osm/models/locality.py, django_project/localities_osm/serializer/locality_osm.py
Fixing completeness doesn't show on sidebar (because not included on API)
=> fixing completeness not show on sidebar

deployment/docker-osm-healthcare/mapping.yml, django_project/core/settings/project.py, django_project/frontend/static/css/map/locality-sidebar.css, django_project/frontend/static/scripts/views/map-sidebar/locality-detail.js, django_project/frontend/templates/map.html, django_project/localities_osm/models/locality.py, django_project/localities_osm/serializer/locality_osm.py, django_project/localities_osm_extension/admin.py, django_project/localities_osm_extension/migrations/0002_auto_20190513_0550.py, django_project/localities_osm_extension/models/extension.py, django_project/localities_osm_extension/models/tag.py, django_project/localities_osm_extension/tests/model_factories.py, django_project/localities_osm_extension/tests/test_locality_osm_extension.py
1. Update mapping.yml
2. Update extension model
3. Add "extension" tags on API and show it on sidebar
Example country is a additional tag
=> Updates mapping and extension model

django_project/core/base_static/css/map.css, django_project/core/settings/contrib.py, django_project/frontend/static/js/locality-sidebar.js, django_project/frontend/templates/map.html, django_project/frontend/templates/sections/map/profile.html, django_project/frontend/templates/sections/map/sidebar-footer.html, django_project/frontend/templates/sections/map/sign-in-modal.html, django_project/social_users/static/css/profile.css, django_project/social_users/templates/social_users/profile.html, django_project/social_users/templates/social_users/signinpage.html
fix #1126 
replacement of PR #1133 
screenshots in #1133
=> add twitter and fb login

deployment/docker/REQUIREMENTS.txt, django_project/api/tests/fixtures/mapping.yml, django_project/api/tests/test_utils.py, django_project/api/utils.py
=> add osm tag converter utility

django_project/api/api_views/v2/facilities/shapefile.py, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/views/map-sidebar/shapefile-downloader.js, django_project/frontend/templates/map.html, django_project/frontend/templates/sections/map/sidebar-default.html, django_project/frontend/templates/sections/map/statistic.html, django_project/localities/management/commands/generate_shapefile_v2.py, django_project/localities_osm/serializer/locality_osm.py
Update shapefile downloader on Map
=> update shapefile downloader

django_project/api/api_views/v2/facilities/cluster.py, django_project/api/management/commands/gen_cluster_cache.py, django_project/api/urls.py, django_project/api/utilities/__init__.py, django_project/api/utilities/clustering.py, django_project/api/utilities/geometry.py, django_project/core/settings/celery_setting.py, django_project/core/settings/project.py, django_project/frontend/static/js/map-functionality.js, django_project/frontend/static/scripts/views/map-sidebar/country-list.js, django_project/frontend/templates/map.html, django_project/frontend/views.py
This fix cluster cache to use osm data
=> fix cluster cache

django_project/frontend/static/scripts/views/map-sidebar/locality-detail.js
Fix url of uploader on sidebar detail
=> fix source of user on detail

django_project/frontend/static/scripts/views/map-sidebar/locality-detail.js, django_project/frontend/templates/sections/map/sidebar-footer.html
=> disabled add/edit button

django_project/frontend/static/scripts/configs/index.js, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/views/map-sidebar/country-list.js, django_project/frontend/static/scripts/views/statistic/request.js, django_project/frontend/static/scripts/views/statistic/view.js, django_project/frontend/templates/index.html, django_project/frontend/views.py
This fix "loading" count of world on frontpage taking long time
=> update country count using count API

django_project/frontend/templates/sections/map/profile.html, django_project/frontend/views.py, django_project/social_users/templates/social_users/profile.html, django_project/social_users/utils.py, django_project/social_users/views.py
this fix error 500 after login if user has multiple social auth
=> fix how social auth works on page

django_project/api/api_views/v2/facilities/detail.py, django_project/frontend/static/js/_app.js, django_project/frontend/static/js/cluster-layer.js, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/views/map-sidebar/locality-detail.js, django_project/frontend/templates/sections/map/locality-detail.html, django_project/localities_osm/serializer/locality_osm.py
- Improve peformance of api detail by checking table based on osm_type
- detail for beds and staff
=> improve peformance of api detail and fix detail of beds and staff

django_project/frontend/static/css/map/locality-sidebar.css, django_project/frontend/templates/sections/map/locality-detail.html
Relayout sidebar to use table instead float
=> relayout detail sidebar

django_project/frontend/templates/index.html, django_project/frontend/templates/sections/navbar.html
fix navbar on map and remove a dead link
=> fix navbar on map and remove a dead link

django_project/api/api_views/v2/get_migration_progress.py, django_project/api/urls.py, django_project/localities/migrations/0019_locality_migrated.py, django_project/localities/models.py, django_project/localities_osm_extension/management/commands/migrate_old_data.py, django_project/localities_osm_extension/migrations/0003_auto_20190515_0551.py, django_project/localities_osm_extension/models/extension.py, django_project/localities_osm_extension/tasks.py, django_project/localities_osm_extension/views.py, django_project/social_users/static/css/profile.css, django_project/social_users/templates/social_users/profile.html, django_project/social_users/urls.py, django_project/social_users/views.py
=> add command to migrate old data

deployment/docker/Dockerfile, deployment/docker/sources.list
=> fix installing certbot on new debian image

django_project/api/osm_tag_defintions.py, django_project/api/tests/test_utils.py, django_project/api/utils.py
=> osm tag defintions and validator

django_project/api/api_views/v2/schema.py, django_project/api/osm_field_definitions.py, django_project/api/tests/test_utils.py, django_project/api/utils.py
=> add field definitions and update schema based on it

django_project/api/api_views/v2/facilities/list.py, django_project/api/fixtures/mapping.yml, django_project/api/fixtures/schema.json, django_project/api/osm_field_definitions.py, django_project/api/utils.py
=> healthsites api to create osm node

django_project/api/api_views/v2/base_api.py, django_project/api/api_views/v2/facilities/base_api.py, django_project/api/api_views/v2/facilities/list.py, django_project/api/api_views/v2/pagination.py, django_project/api/api_views/v2/users/__init__.py, django_project/api/api_views/v2/users/changesets.py, django_project/api/urls.py, django_project/core/settings/prod_docker.py, django_project/frontend/static/js/custom-functions.js, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/shared.js, django_project/frontend/static/scripts/views/statistic/view.js, django_project/localities_osm/serializer/locality_osm.py, django_project/social_users/migrations/0007_auto_20190521_0236.py, django_project/social_users/models.py, django_project/social_users/templates/social_users/profile.html, django_project/social_users/urls.py, django_project/social_users/views.py
- Fix profile bugs that give 500
- Update changeset to use our API V2
=>  fix profile bugs

.gitignore, deployment/docker-compose.yml, django_project/api/api_views/v2/facilities/cluster.py, django_project/api/api_views/v2/facilities/shapefile.py, django_project/api/api_views/v2/get_migration_progress.py, django_project/api/management/commands/generate_shapefile_v2.py, django_project/core/settings/dev_dodobas.py, django_project/core/settings/project.py, django_project/core/settings/test.py, django_project/localities/management/commands/generate_countries_cache.py, django_project/localities/management/commands/generate_shapefile.py, django_project/localities/tasks.py, django_project/localities/utils.py, django_project/localities/views.py, django_project/localities_osm_extension/management/commands/migrate_old_data.py, django_project/social_users/views.py
this fix https://github.com/healthsites/healthsites/issues/1164
=> update cache dir and fix shapefile that does not has osm_id

django_project/core/base_static/css/home.css, django_project/frontend/templates/index.html
=> fix mobile layout

django_project/api/api_views/v2/facilities/cluster.py, django_project/api/utilities/clustering.py, django_project/core/settings/project.py, django_project/frontend/static/js/cluster-layer.js, django_project/frontend/static/js/map-functionality.js, django_project/frontend/templates/map.html, django_project/frontend/views.py
fix #1165 
Before fix:
After fix:
=> no cluster when zoom is max zoom

django_project/api/utils.py, django_project/core/backends/__init__.py, django_project/core/backends/dev_openstreetmap.py, django_project/core/settings/staging_docker.py
this will add staging_docker to change into osm 
https://upload.apis.dev.openstreetmap.org/
=> add "staging" settings that can be changes in docker compose

django_project/api/api_views/v2/facilities/detail.py, django_project/api/osm_api_client.py, django_project/api/utils.py
=> utilities to update and delete osm node

django_project/api/tests/test_osm_api.py
=> unittest for osm node crud operations

django_project/api/api_views/v2/googlemaps/__init__.py, django_project/api/api_views/v2/googlemaps/search.py, django_project/api/urls.py, django_project/core/base_static/css/site.css, django_project/frontend/static/scripts/shared.js, django_project/frontend/static/scripts/views/navbar/search.js, django_project/frontend/templates/sections/navbar.html
=> add place search

django_project/api/api_views/v2/facilities/cluster.py, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/shared.js, django_project/frontend/static/scripts/views/navbar/search.js, django_project/frontend/views.py, django_project/localities_osm/querysets.py
this fixes https://github.com/healthsites/healthsites/issues/1194, fixes https://github.com/healthsites/healthsites/issues/1197
=> Update cluster API

README.md, django_project/api/api_views/v2/facilities/cluster.py, django_project/api/api_views/v2/facilities/list.py, django_project/api/api_views/v2/facilities/search.py, django_project/api/api_views/v2/facilities/shapefile.py, django_project/api/api_views/v2/users/changesets.py, django_project/api/management/commands/generate_cluster_cache.py, django_project/api/management/commands/generate_shapefile_countries.py, django_project/api/management/commands/generate_statistic_countries.py, django_project/api/utilities/statistic.py, django_project/core/settings/base.py, django_project/frontend/views.py, django_project/localities/tasks.py, django_project/localities_osm/queries.py, django_project/localities_osm/utilities.py
this fix https://github.com/healthsites/healthsites/issues/1201
Update statistic to use cache
cache is generated if :
1. cache is not presented
2. cache count is different with actual count
=> update statistic to use cache

django_project/api/api_views/v2/facilities/list.py, django_project/api/tests/test_views.py, django_project/api/urls.py, django_project/api/utils.py, django_project/localities_osm/migrations/0004_auto_20190624_1359.py, django_project/social_users/admin.py, django_project/social_users/migrations/0008_organisation_organizer.py, django_project/social_users/models.py
=> verify organizer or trusted user on osm push api

django_project/core/base_static/css/site.css, django_project/frontend/static/css/map/locality-sidebar.css, django_project/frontend/static/js/map-functionality.js, django_project/frontend/static/js/nav-bar.js, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/shared.js, django_project/frontend/static/scripts/views/map-sidebar/shapefile-downloader.js, django_project/frontend/static/scripts/views/navbar/search.js, django_project/frontend/static/scripts/views/statistic/view.js, django_project/frontend/templates/map.html, django_project/frontend/templates/sections/map/sidebar-footer.html, django_project/frontend/templates/sections/navbar.html
this fix https://github.com/healthsites/healthsites/issues/512
=> add place on url to be shared

deployment/docker/REQUIREMENTS.txt, django_project/api/tests/test_utils.py, django_project/api/utils.py
=> add osm data duplication validation

django_project/api/api_views/v2/facilities/list.py, django_project/frontend/static/css/map/locality-sidebar.css, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/views/map/map.js, django_project/frontend/templates/map.html
=> add search lat long on map

django_project/core/base_static/css/home.css, django_project/frontend/static/scripts/views/statistic/chart.js, django_project/frontend/static/scripts/views/statistic/view.js
fix #439 
Before fix:
After fix:
=> fix graph labels

django_project/api/api_views/v2/base_api.py, django_project/api/api_views/v2/facilities/list.py, django_project/api/utilities/statistic.py, django_project/localities_osm/queries.py
fix #1257 
I added date filters (from and to) to the following apis:
input is timestamp
=> add date filter in facility apis

django_project/api/api_views/v2/facilities/search.py
=> add search in area

django_project/api/api_views/v2/facilities/search.py, django_project/api/api_views/v2/googlemaps/search.py, django_project/api/utils.py, django_project/localities_osm/queries.py
this fixes https://github.com/healthsites/healthsites/issues/421 and https://github.com/healthsites/healthsites/issues/1264
=> fix unicode and update healthsites search by place

.travis.yml, django_project/social_users/utils.py
Fix travis yml because the previous one got error from db creation
`ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory`
=> fix travis

django_project/api/api_views/v2/facilities/list.py, django_project/api/api_views/v2/import_progress.py, django_project/api/importers.py, django_project/api/tasks.py, django_project/api/tests/test_utils.py, django_project/api/urls.py, django_project/api/utils.py, django_project/frontend/static/css/data-loader.css, django_project/localities/admin.py, django_project/localities/forms.py, django_project/localities/migrations/0021_auto_20190719_0414.py, django_project/localities/models.py, django_project/localities/tasks.py, django_project/localities/templates/dataloaderform.html, django_project/localities/urls.py, django_project/localities/views.py
=> New CSV Importer

django_project/core/base_static/css/site.css, django_project/social_users/models.py, django_project/social_users/static/css/profile.css, django_project/social_users/templates/social_users/profile.html, django_project/social_users/templates/social_users/update-profile-modal.html, django_project/social_users/urls.py, django_project/social_users/views.py
this fix https://github.com/healthsites/healthsites/issues/1193
This is how profile show
We have 2 button
When we don't have any key, looks like this
When update profile
When submitted
=> add update profile and auto generate api key

django_project/api/osm_tag_defintions.py, django_project/api/tests/test_utils.py, django_project/frontend/static/scripts/views/map-sidebar/healthsite-detail/form.js
Update form to show speciality options
and also the list will changes based on healthcare that selected
=> update speciality form

django_project/api/api_views/v2/get_migration_progress.py, django_project/api/api_views/v2/utilities.py, django_project/localities/views.py, django_project/localities_osm/utilities.py, django_project/localities_osm_extension/management/commands/migrate_old_data.py, django_project/social_users/templates/social_users/profile.html
this fix https://github.com/healthsites/healthsites/issues/1155
hi @markherringer 
because some of attributes that required is not presented on old healthsite, when migrating, it will call API and show like we upload from ODK
click migrate button
After that, it will show the error on the profile, so we can fix that on map
=> update migrations to use API

django_project/api/api_views/v2/facilities/detail.py, django_project/api/utils.py, django_project/frontend/static/css/map/locality-sidebar.css, django_project/frontend/static/scripts/views/map-sidebar/healthsite-detail/control.js, django_project/frontend/static/scripts/views/map-sidebar/healthsite-detail/detail.js
this fix https://github.com/healthsites/healthsites/issues/1247
hi @markherringer 
this PR will enable edit of way (polygon)
i sucessed edit a way
https://www.openstreetmap.org/way/619348670
For way, latitude/longitude input will be hidden, as well as marker
=> enable way edit

deployment/docker-osm-compose.yml, django_project/api/api_views/v2/get_migration_progress.py
also fixing https://github.com/healthsites/healthsites/issues/1300
=> update docker osm database into version 11 and fix wrong returns

django_project/api/api_views/v2/facilities/shapefile.py, django_project/api/management/commands/generate_shapefile_countries.py, django_project/api/urls.py, django_project/frontend/static/scripts/views/map-sidebar/shapefile-downloader.js
this fix https://github.com/healthsites/healthsites/issues/1308
=> fix shapefile downloader not working on world and country with . in the name

django_project/api/utilities/statistic.py, django_project/frontend/static/css/map/locality-sidebar.css, django_project/frontend/templates/sections/map/statistic.html
this fix https://github.com/healthsites/healthsites/issues/1304
=> update latest update of country to be 20

django_project/api/utils.py, django_project/frontend/templates/map.html
this fix https://github.com/healthsites/healthsites/issues/1314
=> fix data upload for non ascii

README.md, django_project/api/importers.py, django_project/localities/templates/dataloaderform.html
- fix excell template url
- able to receive using hxl csv or not
=> Version 2.0.7

django_project/api/api_views/v2/pagination.py
Add limit in the paramater to change limit of pagination
=> add limit as parameter for pagination

django_project/api/importers.py, django_project/frontend/static/scripts/views/map-sidebar/healthsite-detail/detail.js
=> fix the detail rendering

django_project/api/osm_api_client.py, django_project/api/osm_tag_defintions.py, django_project/api/utils.py, django_project/frontend/static/scripts/shared.js, django_project/frontend/static/scripts/views/map-sidebar/healthsite-detail/control.js, django_project/frontend/static/scripts/views/map-sidebar/healthsite-detail/form.js, django_project/frontend/static/scripts/views/map-sidebar/healthsite-detail/modal/changeset-comment.js, django_project/frontend/templates/map.html, django_project/frontend/templates/sections/modal/changeset-comment.html
Add changeset comment and source
form
after saved
=> add changeset comment and source

README.md, deployment/Makefile
this fix https://github.com/healthsites/healthsites/issues/1393
=> update readme setup

django_project/api/api_views/v2/facilities/cluster.py, django_project/api/urls.py
For #1363 
Example request : 
```/api/v2/filter-osm-data/?healthcare=doctor,clinic```
Will return sql view name, which the Geoserver can load.
=> Add osm filter backend

django_project/core/base_static/css/map.css, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/views/map-sidebar/filter.js, django_project/frontend/templates/map.html
=> add front end filter

README.md, django_project/api/LICENSE.txt, django_project/api/README.md, django_project/api/management/commands/generate_shapefile_countries.py, django_project/api/management/commands/generate_statistic_countries.py, django_project/core/base_static/css/map.css, django_project/core/settings/project.py, django_project/frontend/static/scripts/views/map/map.js
this fix https://github.com/healthsites/healthsites/issues/1427
hi @timlinux 
can you review this PR, mostly for the content of license
what i changes
- add data credits on readme : https://github.com/healthsites/healthsites/compare/develop...meomancer:1427-odbl-license?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R30
- add license.txt that will be included into shapefile zip https://github.com/meomancer/healthsites/blob/d539701bd0ad1ab0074f6360582cdd05309364af/django_project/api/LICENSE.txt
- add readme.md that will be included into shapefile.zip
https://github.com/meomancer/healthsites/blob/d539701bd0ad1ab0074f6360582cdd05309364af/django_project/api/README.md
- When on basemap esri, add "data license" on the attribution for osm …
=> update license and add license on the shapefile

django_project/api/api_views/v2/countries/search.py, django_project/api/api_views/v2/schema.py
this fix https://github.com/healthsites/healthsites/issues/1411
=> add parameters on autocomplete docs

django_project/core/base_static/css/map.css, django_project/frontend/static/scripts/configs/map.js, django_project/frontend/static/scripts/views/map-sidebar/country-list.js, django_project/frontend/templates/map.html, django_project/frontend/templates/sections/map/statistic.html, django_project/frontend/views.py, django_project/localities/data/osm_boundaries/country_data.json, django_project/localities/management/commands/generate_countries.py, django_project/localities/migrations/0023_auto_20200429_0838.py, django_project/localities/models.py
this fix https://github.com/healthsites/healthsites/issues/1410
Add continent data on map
- statistic
- shapefile
Screenshoots
instead A-Z accordion, change to the continent (already make sure every country has continent)
Click the name of continent to enter it's page
Can download shapefile too
At the bottom pf page, there is country list of the continent
=> Continent data

django_project/frontend/templates/envelope/contact.html
this fix https://github.com/healthsites/healthsites/issues/1450
Added captcha 3 into form
CC @markherringer :
i need capcha key from your google. This PR is from my google and it is still testing key.
Can be added in here:
https://www.google.com/recaptcha/admin/create
Fill **Domains** to healthsites.io
=> add captcha into contact form

django_project/api/api_views/v2/facilities/detail.py, django_project/api/api_views/v2/facilities/list.py, django_project/core/settings/project.py
this fix https://github.com/healthsites/healthsites/issues/1455
hi @nixilla 
could you review this? i don't have access to sentry
=> add test user setting to raise error to sentry

django_project/frontend/static/scripts/views/navbar/search.js
this fix https://github.com/healthsites/healthsites/issues/1457
Adding system to send what user search into google analytics event
can be check in 
- Real-time -> Events 
- Behaviours -> Events -> Overview
The format will be
**Event Action** -> [Search Type]=[Search Value]
Example: Healthsites=Main Hospi
=> send user search to google analytics event
